### ISSUE TITLE
media Daten error 404

### ISSUE THREAD

**Issue by chrisrex** [FriendsOfREDAXO/demo_uikit3#2]
der Pfad zu den Media Daten scheint nicht zu stimmen. Fehler 404.
Redaxo läuft in einem Unterverzeichnis ohne yrewrite.
Eventuell stört der Slash vor dem Verzeichnis media

**Comment by skerbis** [comment]
Ja es gibt noch fest verdrahtete URLs , wird korrigiert

**Comment by skerbis** [comment]
Sollte erledigt sein.
